### PR TITLE
Fixing destination arg

### PR DESCRIPTION
**Pull request by nathanathan**

### CODE REVIEW

**Comment by adjohnson916** [comment]
@mrcoles Please merge?

**Comment by mrcoles** [comment]
Sure, thx for the heads up @adjohnson916 😆

**Comment by mrcoles** [comment]
I added a couple more updates and launched on npm as v0.0.5: https://github.com/mrcoles/bookmarklet/compare/d405f9ddbe962f9a32fb36acc1f0928df2bc53a0...0.0.5

**Comment by adjohnson916** [comment]
@mrcoles thanks!

**Pull request merged**
